### ISSUE TITLE
fixing alert texts on anmeldung.php

### ISSUE THREAD

**Issue by multireadsts** [Andreas-Schoenefeldt/viszerale-therapie.at#11]
I did this directly before using github via ftp:
Please adopt to github repository ..

**Comment by Andreas-Schoenefeldt** [comment]
Ok, then it is probably lost now... I'll check it out

Am 15/12/2015 um 18:42 schrieb multireadsts:

**Comment by multireadsts** [comment]
Ive a local copy to put in my branch if needed
