### ISSUE TITLE
Warnings appear after finished registration

### ISSUE THREAD

**Issue by nataliko** [Andreas-Schoenefeldt/viszerale-therapie.at#2]
http://lotus-moon.de/Proj/viszerale-therapie.at/anmeldung2.php
On top of the page

Notice: Undefined variable: datenterm in /var/www/vhosts/lotus-moon.de/httpdocs/Proj/viszerale-therapie.at/anmeldung2.php on line 25

Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in /var/www/vhosts/lotus-moon.de/httpdocs/Proj/viszerale-therapie.at/anmeldung2.php on line 28

![screen shot 2015-12-11 at 16 03 02](https://cloud.githubusercontent.com/assets/16244792/11748563/ca9ccc92-a020-11e5-8cf6-0deb49fa7f78.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Shatzi, this should be fixed now - could you retest this please and if it is realy gone close the ticket?

Thx a lot
Andreas

**Comment by nataliko** [comment]
Sure, I will do that tomorrow. I like evenings and weekends free from work.
-- 
Best wishes,
Natalia Gomolka
07874 954 417

skype: ngomolka

______________
Everything is a dream, that's why everything is possible.

**Comment by nataliko** [comment]
Yep, it's gone.
