### ISSUE TITLE
Therapist List Icons are not shown anymore

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/viszerale-therapie.at#22]
Hi Stefan,

I noticed that the therapist list http://www.viszerale-therapie.at/therapeuten.php looks broken at the moment. Icons and images seem to be missing. 

Tested on Mac OS X and Firefox/Chrome 
I did a few deployments in the last days, do you see if something wen't missing inbetween?

Thx for checking
Andreas

**Comment by multireadsts** [comment]
Hi Andreas,

in the frontend I see only a displaced heading. 
If you're still busy on issues please fix that css too - THX!

- Stefan
-----Original Message-----

**Comment by Andreas-Schoenefeldt** [comment]
You are right, looks like a temporary missfunction of my browser - I fixed the css.
